# Generated by Django 4.2.16 on 2024-11-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('salary', 'Salary'), ('entertainment', 'Entertainment'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
