# Generated by Django 4.2.16 on 2024-11-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager_app', '0002_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='title',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('salary', 'Зарплата'), ('other', 'Другие источники'), ('mandatory', 'Обязательные расходы'), ('food', 'Продукты'), ('car', 'Автомобиль'), ('entertainment', 'Развлечения'), ('home_goods', 'Товары для дома'), ('self_care', 'Забота о себе'), ('education', 'Образование'), ('other', 'Разное')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('IN', 'Доход'), ('OUT', 'Расход')], max_length=3),
        ),
    ]
