# Generated by Django 4.2.16 on 2024-11-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager_app', '0004_remove_transaction_category_remove_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category_expense',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category_income',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
